### ISSUE TITLE
access_base module installation error

### ISSUE THREAD

**Issue by danielegobbetti** [itpp-labs/misc-addons#1]
Hello @yelizariev ! Thanks for this collection of script, they could help me a lot since I am planning to migrate from sugarCRM to odoo.

My problem is that I cannot install the module sugarcrm_import, because the dependency access_base is failing to install. I am using the debian packages of odoo 8.00 and am getting the following error:
Odoo Server Error
[... snipped first part of the stacktrace ...]
  File "/usr/lib/python2.7/dist-packages/openerp/addons/access_base/models.py", line 22, in update_user_groups_view
    custom_group_id = self.pool['ir.model.data'].get_object_reference(cr, uid, 'access_base', 'module_category_custom')[1]
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_model.py", line 966, in get_object_reference
    return self.xmlid_lookup(cr, uid, "%s.%s" % (module, xml_id))[1:3]
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "<string>", line 2, in xmlid_lookup
  File "/usr/lib/python2.7/dist-packages/openerp/tools/cache.py", line 71, in lookup
    value = d[key] = self.method(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_model.py", line 924, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ValueError: External ID not found in the system: access_base.module_category_custom

And the module remains in the state "pending installation".

I manually installed all the other dependencies and identified this addon to be the culprit. I installed odoo only yesterday, hence I have no idea how to dig deeper into this issue, I would appreciate any help.

Kind regards,
Daniele

**Comment by yelizariev** [comment]
Hi @danielegobbetti 

What is the sugarcrm_import module? In my repo there is only sugarcrm_migration module. The sugarcrm_migration module is not ready-to-use. It's only for specific need of a specific customer. But it can be used as a base to make new module.

The log you provided doesn't explain why access_base failed to install. It only says that access_base is not installed. You can try to install access_base and give me a another log. But I don't think you actually need access_base module.  I use this module only to make other modules with specific customer requirements about access rights.

Any way feel free to use my modules.

I can recommend web_last_viewed_records module -- it implements the same future as in SugarCRM

**Comment by yelizariev** [comment]
Also, there is note in module's description abou exact version of odoo.

```
Tested on odoo 8.0 ab7b5d7732a7c222a0aea45bd173742acd47242d
```

So, you can try to switch to this revision:

```
git checkout ab7b5d7732a7c222a0aea45bd173742acd47242d
```

**Comment by danielegobbetti** [comment]
Thanks for the prompt reply!

My bad, I misspelled the module name, I was referring to sugarcrm_migration. Sorry for that.

Among its dependencies there is sale_mediation_custom which depends on access_base which gives the error you find at the end of this message (complete stacktrace) while installing.

My aim is to import as much data as possible from sugarCRM to odoo but we are not using kashflow, does the module work in this scenario?

Thanks again and regards.

The stacktrace follows:

2015-01-08 15:29:36,379 6977 INFO Peer openerp.modules.module: module access_base: creating or updating database tables
2015-01-08 15:29:36,661 6977 ERROR Peer openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 518, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 539, in dispatch
    result = self._call_function(*_self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 295, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 292, in checked_call
    return self.endpoint(_a, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 755, in __call__
    return self.method(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 388, in response_wrap
    response = f(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/registry.py", line 346, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 363, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 163, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/module.py", line 287, in init_module_models
    obj.init(cr)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/share/res_users.py", line 62, in init
    self.update_user_groups_view(cr, SUPERUSER_ID)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/access_base/models.py", line 22, in update_user_groups_view
    custom_group_id = self.pool['ir.model.data'].get_object_reference(cr, uid, 'access_base', 'module_category_custom')[1]
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_model.py", line 966, in get_object_reference
    return self.xmlid_lookup(cr, uid, "%s.%s" % (module, xml_id))[1:3]
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "<string>", line 2, in xmlid_lookup
  File "/usr/lib/python2.7/dist-packages/openerp/tools/cache.py", line 71, in lookup
    value = d[key] = self.method(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_model.py", line 924, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ValueError: External ID not found in the system: access_base.module_category_custom

**Comment by yelizariev** [comment]
Try to use parametr

```
-u access_base 
```

in shell, when you start odoo.

Any way, some manual work has to be done with sugarcrm_migration module, because current version also depends on serious modification of odoo which I made for my customer and which probably you don't need.

Also, sale_mediation_custom was continued to develop without using sugarcrm_migration. So, I am not sure, that current version of sugarcrm_migration works.

My modules are published without any warranty. I can fix some issue, if they are interesting to me. For anything else you can hire me via odesk https://www.odesk.com/users/~01d05f689c5d7ce2f3

**Comment by danielegobbetti** [comment]
Thanks a lot! I'll try. 

I did not know about the odesk website. It certainly looks interesting. Just a question if I may ask: in your experience it is possible to get some data from sugarcrm into odoo (client list, leads, archives of calls, we are not using much more of sugarcrm (e.g. we don't use tasks, projects, etc.)) and would it take much time (for you to adapt the plugin)? Of course a broad estimate! :)

**Comment by yelizariev** [comment]
sugarcrm_import do it: you upload dump of your sugarcrm database, then sugarcrm records are converted to odoo records using "mapping rules". This mapping rules can be changed only in module source.
Try to create project at odesk and will get my offer.
