### ISSUE TITLE
[13.0] odoo_backup_sh: Error QWeb2: Template 'odoo_backup_sh.BackupDashboardMain' not found

### ISSUE THREAD

**Issue by jack-nbv** [itpp-labs/misc-addons#1012]
Hi, I installed the module **odoo_backup_sh** locally on odoo 13 and got this error:

Traceback:
Error: QWeb2: Template 'odoo_backup_sh.BackupDashboardMain' not found
    at Object.exception (http://localhost:8069/web/content/1091-ec334de/web.assets_common.js:3692:7)
    at Engine._render (http://localhost:8069/web/content/1091-ec334de/web.assets_common.js:3737:103)
    at Engine.render (http://localhost:8069/web/content/1091-ec334de/web.assets_common.js:3733:151)
    at Class.renderElement (http://localhost:8069/web/content/1268-1872c5a/web.assets_backend.js:472:357)
    at Class.prototype.<computed> [as renderElement] (http://localhost:8069/web/content/1091-ec334de/web.assets_common.js:3861:488)
    at http://localhost:8069/web/content/1091-ec334de/web.assets_common.js:4103:6
    at mightThrow (http://localhost:8069/web/content/1091-ec334de/web.assets_common.js:914:18)
    at process (http://localhost:8069/web/content/1091-ec334de/web.assets_common.js:916:89)

**Comment by nmoturi** [comment]
Same issue encountered in V14.

**Comment by trojikman** [comment]
recently launched this module on 13.0 and 14.0, works fine.
Maybe the static folder didn't load, usually restarting help
