### ISSUE TITLE
[11.0 ir_attachment_url: Maximum recursion depth exceeded

### ISSUE THREAD

**Issue by sotolucas** [itpp-labs/misc-addons#1041]

**Comment by sotolucas** [comment]
Hi there!
I'm facing a bug while trying to install the module ir_attachment_url
The trace is:
```
2020-11-30 02:10:47,631 29 INFO odoo werkzeug: 190.19.100.249 - - [30/Nov/2020 02:10:47] "POST /web/webclient/version_info HTTP/1.1" 500 -
2020-11-30 02:10:47,777 29 ERROR odoo werkzeug: Error on request:
Traceback (most recent call last):
  File "/home/odoo/.local/lib/python3.5/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/home/odoo/.local/lib/python3.5/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/custom/src/odoo/odoo/service/wsgi_server.py", line 178, in application
    return ProxyFix(application_unproxied)(environ, start_response)
  File "/home/odoo/.local/lib/python3.5/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/custom/src/odoo/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1321, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1295, in __call__
    return self.app(environ, start_wrapped)
  File "/home/odoo/.local/lib/python3.5/site-packages/werkzeug/wsgi.py", line 766, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1476, in dispatch
    odoo.registry(db).check_signaling()
  File "/opt/odoo/custom/src/odoo/odoo/__init__.py", line 76, in registry
    return modules.registry.Registry(database_name)
  File "/opt/odoo/custom/src/odoo/odoo/modules/registry.py", line 61, in __new__
    return cls.new(db_name)
  File "/opt/odoo/custom/src/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 383, in load_modules
    registry.setup_models(cr)
  File "/opt/odoo/custom/src/odoo/odoo/modules/registry.py", line 275, in setup_models
    model._setup_base()
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 2413, in _setup_base
    if not field.related:
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 332, in __getattr__
    return self._attrs[name]
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 332, in __getattr__
    return self._attrs[name]
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 332, in __getattr__
    return self._attrs[name]
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 332, in __getattr__
    return self._attrs[name]
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 332, in __getattr__
    return self._attrs[name]
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 332, in __getattr__
    return self._attrs[name]
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 332, in __getattr__
    return self._attrs[name]
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 332, in __getattr__
    return self._attrs[name]
RecursionError: maximum recursion depth exceeded
```
Any clue on this?
Thank you.
PD: I've also tried to start the server with the server_wide_modules=web,ir_attachment_url as documentation says but the result is the same.

**Comment by trojikman** [comment]
Hello!

Thanks for your feedback!
I checked how module works on 11.0 but did not face the problem you're talking about. Maybe you made a mistake in starting the Odoo or somewhere else?

If you have additional questions or more context, feel free to reopen the issue

Regards
