### ISSUE TITLE
[13.0-14.0] odoo_backup_sh: get Access denied when list_db=False

### ISSUE THREAD

**Issue by trojikman** [itpp-labs/misc-addons#1113]
Steps to reproduce:

1. as mentioned set `list_db = False` in odoo.conf
2. insert and uncomment this code https://github.com/itpp-labs/misc-addons/commit/d5eeae9662ca72613d800f1b6725aaec1726aefe
3. Make a backup manually or wait until it starts by schedule
4. Get this error:
```
odoo_1   | 2021-05-04 14:07:46,240 31 INFO backup odoo.addons.base.models.ir_cron: Starting job `Odoo-backup.sh: Backup the "backup" database, send it to odoo_backup_sh storage, apply rotation`. 
odoo_1   | 2021-05-04 14:07:46,263 31 ERROR backup odoo.service.db: Database management functions blocked, admin disabled database listing 
odoo_1   | 2021-05-04 14:07:46,263 31 ERROR backup odoo.addons.base.models.ir_cron: Call from cron Odoo-backup.sh: Backup the "backup" database, send it to odoo_backup_sh storage, apply rotation for server action #139 failed in Job #11 
odoo_1   | Traceback (most recent call last):
odoo_1   |   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_cron.py", line 110, in _callback
odoo_1   |     self.env['ir.actions.server'].browse(server_action_id).run()
odoo_1   |   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions.py", line 534, in run
odoo_1   |     res = func(action, eval_context=eval_context)
odoo_1   |   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions.py", line 419, in run_action_code_multi
odoo_1   |     safe_eval(action.sudo().code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
odoo_1   |   File "/usr/lib/python3/dist-packages/odoo/tools/safe_eval.py", line 354, in safe_eval
odoo_1   |     return unsafe_eval(c, globals_dict, locals_dict)
odoo_1   |   File "", line 1, in <module>
odoo_1   |   File "/mnt/addons/misc-addons/odoo_backup_sh/models/odoo_backup_sh.py", line 695, in make_backup
odoo_1   |     name, service, ts
odoo_1   |   File "/mnt/addons/misc-addons/odoo_backup_sh/models/odoo_backup_sh.py", line 636, in get_dump_stream_and_info_file
odoo_1   |     dump_stream = odoo.service.db.dump_db(name, None, "zip")
odoo_1   |   File "<decorator-gen-9>", line 2, in dump_db
odoo_1   |   File "/usr/lib/python3/dist-packages/odoo/service/db.py", line 39, in if_db_mgt_enabled
odoo_1   |     raise AccessDenied()
odoo_1   | odoo.exceptions.AccessDenied: Access denied
```
Expected behavior: backup done as expected
Affected versions: it tested only on 13.0, 14.0; after fix needs to check other versions

**Comment by yelizariev** [comment]
Related commit in odoo: https://github.com/odoo/odoo/commit/b02dea768814f878bffe9ff1f42304a45d3189de

**Comment by yelizariev** [comment]
Похоже надо еще код добавить, который пользователь сам должен раскомментировать

В этом месте:

https://github.com/itpp-labs/misc-addons/blob/75d43cad3652c6f2f77da0f36f073bbdfe68a09b/odoo_backup_sh/models/odoo_backup_sh.py#L636


Добавить в виде комментария следующей код (я частично протестировал в шеле)

``` py
from unittest.mock import patch                                                                                       
with patch.dict(odoo.tools.config.options, {'list_db': True}):
     dump_stream = odoo.service.db.dump_db(name, None, "zip") 
```

**Comment by trojikman** [comment]
> Похоже надо еще код добавить, который пользователь сам должен раскомментировать
> 
> В этом месте:
> 
> https://github.com/itpp-labs/misc-addons/blob/75d43cad3652c6f2f77da0f36f073bbdfe68a09b/odoo_backup_sh/models/odoo_backup_sh.py#L636
> 
> Добавить в виде комментария следующей код (я частично протестировал в шеле)
> 
> ```python
> from unittest.mock import patch                                                                                       
> with patch.dict(odoo.tools.config.options, {'list_db': True}):
>      dump_stream = odoo.service.db.dump_db(name, None, "zip") 
> ```

С этим работает, а вот [это](https://github.com/itpp-labs/misc-addons/commit/d5eeae9662ca72613d800f1b6725aaec1726aefe#commitcomment-49414771) судя по всему не актуально. Надо дополнительно в 14 протестировать

**Comment by yelizariev** [comment]
Актуально -- ты иначе не сможешь выбрать другие базы

**Comment by trojikman** [comment]
The issue is fixed in v13 but we need [this](https://github.com/itpp-labs/misc-addons/pull/1114/commits/fbc3aa603e2e34520b4108857350a8f6368c497a) commit in v14 at least
