### ISSUE TITLE
Error on creating phonecall with reminder_base and reminder_phoncall module installed 

### ISSUE THREAD

**Issue by dnl-re** [itpp-labs/misc-addons#120]
Hi Ivan,

first of all, thanks for youre awesome modules!

I received following error when I click on Sales -> Logged Calls and want to add a phone call. This happens after installing the reminder_base and the reminder_phonecall module on a fresh database.

```
Traceback (most recent call last):
  File "/home/tertia/workspace/odoo8/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/tertia/workspace/odoo8/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/home/tertia/workspace/odoo8/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/tertia/workspace/odoo8/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/tertia/workspace/odoo8/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/tertia/workspace/odoo8/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/home/tertia/workspace/odoo8/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/home/tertia/workspace/odoo8/openerp/addons/web/controllers/main.py", line 936, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/tertia/workspace/odoo8/openerp/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/tertia/workspace/odoo8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/tertia/workspace/odoo8/openerp/addons/mail/mail_thread.py", line 384, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
  File "/home/tertia/workspace/odoo8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/tertia/workspace/odoo8/openerp/api.py", line 336, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/tertia/workspace/odoo8/openerp/addons/reminder_base/reminder_base_models.py", line 120, in create
    vals = self._check_and_create_reminder_event(vals)
  File "/home/tertia/workspace/odoo8/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/tertia/workspace/odoo8/openerp/addons/reminder_base/reminder_base_models.py", line 114, in _check_and_create_reminder_event
    event = self._create_reminder_event()
  File "/home/tertia/workspace/odoo8/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/tertia/workspace/odoo8/openerp/addons/reminder_base/reminder_base_models.py", line 32, in _create_reminder_event
    event = self.env['calendar.event'].with_context(no_mail_to_attendees=True).create(vals)
  File "/home/tertia/workspace/odoo8/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/tertia/workspace/odoo8/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/home/tertia/workspace/odoo8/openerp/addons/crm/calendar_event.py", line 36, in create
    res = super(calendar_event, self).create(cr, uid, vals, context=context)
  File "/home/tertia/workspace/odoo8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/tertia/workspace/odoo8/openerp/addons/calendar/calendar.py", line 1646, in create
    res = super(calendar_event, self).create(cr, uid, vals, context=context)
  File "/home/tertia/workspace/odoo8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/tertia/workspace/odoo8/openerp/addons/mail/mail_thread.py", line 384, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
  File "/home/tertia/workspace/odoo8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/tertia/workspace/odoo8/openerp/api.py", line 336, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/tertia/workspace/odoo8/openerp/models.py", line 4059, in create
    record = self.browse(self._create(old_vals))
  File "/home/tertia/workspace/odoo8/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/tertia/workspace/odoo8/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/home/tertia/workspace/odoo8/openerp/models.py", line 4179, in _create
    self._check_selection_field_value(cr, user, field, vals[field], context=context)
  File "/home/tertia/workspace/odoo8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/tertia/workspace/odoo8/openerp/api.py", line 336, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/tertia/workspace/odoo8/openerp/models.py", line 2245, in _check_selection_field_value
    field.convert_to_cache(value, self)
  File "/home/tertia/workspace/odoo8/openerp/fields.py", line 1389, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for calendar.event.state: 'done'
```

**Comment by yelizariev** [comment]
It Seems like somewhere there is wrong default value for field state in calendar.event, because
in line 32 https://github.com/yelizariev/addons-yelizariev/blob/8.0/reminder_base/reminder_base_models.py#L32
the module just create record without state

```
@api.model
def _create_reminder_event(self):
    vals = {
        'reminder_res_model': self._name,
        # dummy values
        'name': 'TMP NAME',
        'allday': True,
        'start_date': fields.Date.today(),
        'stop_date': fields.Date.today(),
    }
    event = self.env['calendar.event'].with_context(no_mail_to_attendees=True).create(vals)
    return event
```

**Comment by yelizariev** [comment]
Or somewhere else field state is added

```
File "/home/tertia/workspace/odoo8/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/tertia/workspace/odoo8/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/home/tertia/workspace/odoo8/openerp/addons/crm/calendar_event.py", line 36, in create
    res = super(calendar_event, self).create(cr, uid, vals, context=context)
  File "/home/tertia/workspace/odoo8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/tertia/workspace/odoo8/openerp/addons/calendar/calendar.py", line 1646, in create
    res = super(calendar_event, self).create(cr, uid, vals, context=context)
  File "/home/tertia/workspace/odoo8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/tertia/workspace/odoo8/openerp/addons/mail/mail_thread.py", line 384, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
```

**Comment by dnl-re** [comment]
So is there a problem with my Odoo installation or is this a bug in the module? Either way, how could I fix it without deep knowledge of the crm_module or the event model? Every advice is appreciated. Thanks in advance!

**Comment by yelizariev** [comment]
I got it. New values is added from context.
Thank you for reporting

**Comment by yelizariev** [comment]
Please check new version
