### ISSUE TITLE
reminder error self._get_duration(values['start']

### ISSUE THREAD

**Issue by 360org** [itpp-labs/misc-addons#345]
Hello i have install successful misc-addons but when i start to create reminder it show error in the crm like that plz help.

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/Software/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/Software/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/Software/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/Software/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/Software/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/Software/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/Software/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/Software/addons/web/controllers/main.py", line 862, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/Software/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/Software/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/Software/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/Software/addons/crm/models/crm_lead.py", line 315, in write
    return super(Lead, self).write(vals)
  File "/usr/lib/python2.7/dist-packages/Software/addons/mail/models/mail_thread.py", line 274, in write
    result = super(MailThread, self).write(values)
  File "<decorator-gen-284>", line 2, in write
  File "/usr/lib/python2.7/dist-packages/Software/api.py", line 361, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/home/Software/misc-addons/reminder_base/reminder_base_models.py", line 133, in write
    vals = self._check_and_create_reminder_event(vals)
  File "/home/Software/misc-addons/reminder_base/reminder_base_models.py", line 119, in _check_and_create_reminder_event
    event = self._create_reminder_event()
  File "/home/Software/misc-addons/reminder_base/reminder_base_models.py", line 37, in _create_reminder_event
    }).create(vals)
  File "/usr/lib/python2.7/dist-packages/Software/addons/crm/models/calendar.py", line 15, in create
    event = super(CalendarEvent, self).create(vals)
  File "/usr/lib/python2.7/dist-packages/Software/addons/calendar/models/calendar.py", line 1399, in create
    values['duration'] = self._get_duration(values['start'], values['stop'])
KeyError: 'start'

**Comment by yelizariev** [comment]
Fixed here https://github.com/it-projects-llc/misc-addons/pull/348
