### ISSUE TITLE
reminder: can't convert some leads to opportunities

### ISSUE THREAD

**Issue by miscs** [itpp-labs/misc-addons#40]
Hi,

with activated reminder plugins I have trouble converting some of my leads (not all) to opportunities. Error log shows the following error:

2015-09-01 14:59:50,876 29383 ERROR database openerp.sql_db: Programming error: column "res_partner_id" is of type integer but expression is of type boolean
LINE 1: ...r_rel (calendar_event_id,res_partner_id) values (639, false)
                                                                 ^
HINT:  You will need to rewrite or cast the expression.
, in query insert into calendar_event_res_partner_rel (calendar_event_id,res_partner_id) values (%s, %s)
2015-09-01 14:59:50,877 29383 ERROR database openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/addons/crm/wizard/crm_lead_to_opportunity.py", line 161, in action_apply
    self._convert_opportunity(cr, uid, ids, vals, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/addons/crm/wizard/crm_lead_to_opportunity.py", line 120, in _convert_opportunity
    res = lead.convert_opportunity(cr, uid, [lead_id.id], partner_id, [], False, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/addons/crm/crm_lead.py", line 726, in convert_opportunity
    self.write(cr, uid, [lead.id], vals, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 363, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/odoo-server/addons/crm_lead_lost_reason/model/crm_lead.py", line 54, in write
    result = super(CrmLead, self).write(vals)
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 547, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_kwargs)
  File "/opt/odoo/odoo-server/addons/crm/crm_lead.py", line 953, in write
    return super(crm_lead, self).write(cr, uid, ids, vals, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/addons/mail/mail_thread.py", line 432, in write
    result = super(mail_thread, self).write(cr, uid, ids, values, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 394, in old_api
    result = new_api(recs, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 398, in new_api
    result = [method(rec, _args, *_kwargs) for rec in self]
  File "/opt/odoo/odoo-server/addons/reminder_base/reminder_base_models.py", line 130, in write
    self._update_reminder(vals)
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 398, in new_api
    result = [method(rec, _args, *_kwargs) for rec in self]
  File "/opt/odoo/odoo-server/addons/reminder_base/reminder_base_models.py", line 55, in _update_reminder
    self._do_update_reminder(update_date=self._reminder_date_field in vals)
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 398, in new_api
    result = [method(rec, _args, *_kwargs) for rec in self]
  File "/opt/odoo/odoo-server/addons/reminder_base/reminder_base_models.py", line 107, in _do_update_reminder
    event.write(vals)
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 547, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_kwargs)
  File "/opt/odoo/odoo-server/addons/calendar/calendar.py", line 1613, in write
    res = super(calendar_event, self).write(cr, uid, [int(event_id) for event_id in ids], values, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/addons/mail/mail_thread.py", line 432, in write
    result = super(mail_thread, self).write(cr, uid, ids, values, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 363, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 3778, in write
    self._write(old_vals)
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 547, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 3921, in _write
    result += self._columns[field].set(cr, self, id, field, vals[field], user, context=rel_context) or []
  File "/opt/odoo/odoo-server/openerp/osv/fields.py", line 1052, in set
    cr.execute('insert into '+rel+' ('+id1+','+id2+') values (%s, %s)', (id, act_nbr))
  File "/opt/odoo/odoo-server/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column "res_partner_id" is of type integer but expression is of type boolean
LINE 1: ...r_rel (calendar_event_id,res_partner_id) values (639, false)
                                                                 ^
HINT:  You will need to rewrite or cast the expression.

**Comment by yelizariev** [comment]
Thank you, 
we will fix it soon
