### ISSUE TITLE
Backend Debranding Module

### ISSUE THREAD

**Issue by mfaheemkhan6** [itpp-labs/misc-addons#546]
After installing backend debranding module, I am unable to send a quotation by email. Following error occurs.
`Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 885, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
TypeError: create() takes exactly 2 arguments (1 given)`

To reproduce this error. create a quotation and click "Send Email" button. Email menu will be open, the email will be sent. Now install web_debranding and again open previously created quotation and try sending quotation email. This error will occur.

**Comment by mfaheemkhan6** [comment]
I am using odoo 10.0

**Comment by yelizariev** [comment]
Thanks for reporting :+1:
