### ISSUE TITLE
[10.0]Conflict with  currency_rate_update

### ISSUE THREAD

**Issue by flotho** [itpp-labs/misc-addons#563]
Hi,
Running an Oodo 10.0 with your repo in the class path cause issue due to this module and reference to orm.
Is it normal that installable and active flags are not considered?
Regards

**Comment by ilmir-k** [comment]
Hi @flotho 

The module currency_rate_update has not been migrated to 10.0 yet, so it is non installable:
`"Installable": False`

**Comment by flotho** [comment]
Hi @ilmir-k , you're right, we saw this, yet during an 'update all' process, it throws an error :

```
WARNING ? odoo.api: Deprecated method CurrencyRateUpdateService._check_max_delta_days in module odoo.addons.currency_rate_update.currency_rate_update
2018-03-25 14:31:13,678 2474 WARNING ? odoo.api: Deprecated method CurrencyRateUpdate.get_cron_id in module odoo.addons.currency_rate_update.currency_rate_update
2018-03-25 14:31:13,678 2474 WARNING ? odoo.api: Deprecated method CurrencyRateUpdate.save_cron in module odoo.addons.currency_rate_update.currency_rate_update
2018-03-25 14:31:13,678 2474 WARNING ? odoo.api: Deprecated method CurrencyRateUpdate.run_currency_update in module odoo.addons.currency_rate_update.currency_rate_update
2018-03-25 14:31:13,679 2474 INFO ? werkzeug: 151.80.220.226 - - [25/Mar/2018 14:31:13] "GET /web HTTP/1.1" 500 -
2018-03-25 14:31:13,683 2474 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/home/odoo/server/odoo/service/server.py", line 246, in app
    return self.app(e, s)
  File "/home/odoo/server/odoo/service/wsgi_server.py", line 184, in application
    return werkzeug.contrib.fixers.ProxyFix(application_unproxied)(environ, start_response)
  File "/usr/lib/python2.7/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "/home/odoo/server/odoo/service/wsgi_server.py", line 172, in application_unproxied
    result = handler(environ, start_response)
  File "/home/odoo/server/odoo/http.py", line 1322, in __call__
    self.load_addons()
  File "/home/odoo/server/odoo/http.py", line 1343, in load_addons
    m = __import__('odoo.addons.' + module)
  File "/home/odoo/server/odoo/modules/module.py", line 81, in load_module
    execfile(modfile, new_mod.__dict__)
  File "/home/odoo/additionnal_repositories/IT-projects-misc-addons/currency_rate_update/__init__.py", line 25, in <module>
    from . import company
  File "/home/odoo/additionnal_repositories/IT-projects-misc-addons/currency_rate_update/company.py", line 22, in <module>
    from openerp import fields, orm
  File "/home/odoo/server/odoo/modules/module.py", line 109, in load_module
    mod = importlib.import_module(canonical)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named orm

```
Of course we could propose a little PR to 'hide' this but we're wondering why the active and not instllable flags seems to not be taken into account during an update all process.

**Comment by ilmir-k** [comment]
Hi @flotho 
Yes. It's strangely enough. 
@yelizariev please look at this. Do you have any suggestions?

**Comment by carlosrve** [comment]
The problem is that depending on the continuous integration configuration, it does or does not takes into account the installable flag, so it may still try to test this module.

For example, in Odoo.sh it does test all custom modules, including not installable ones.
