### ISSUE TITLE
[ir_config_parameter_multi_company] breaks with recent Odoo 11 commits

### ISSUE THREAD

**Issue by jladage** [itpp-labs/misc-addons#567]
When using ir_config_parameter_multi_company with Odoo 11. Running a odoo-bin -u all fails with the error below. This happens since they replaced password with session_token. In base/res/res_users.py in the _compute_session_token method in line 526 they use a raw SQL query to fetch a parameter.

```
    @tools.ormcache('sid')
    def _compute_session_token(self, sid):
        """ Compute a session token given a session id and a user id """
        # retrieve the fields used to generate the session token
        session_fields = ', '.join(sorted(self._get_session_token_fields()))
        self.env.cr.execute("""SELECT %s, (SELECT value FROM ir_config_parameter WHERE key='database.secret')
                                FROM res_users
                                WHERE id=%%s""" % (session_fields), (self.id,))
```

I'm not sure whether this should be fixed there or we could work our way around it in this module.

```
2018-03-23 13:49:26,137 66412 ERROR ladageodoodev odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/Users/jladage/git/ladage.odoo/parts/odoo/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/Users/jladage/git/ladage.odoo/parts/odoo/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/jladage/git/ladage.odoo/parts/odoo/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('res.users', <function Users._compute_session_token at 0x10ec979d8>, '325fd259dac2601a16431961d8dde100e14eb1c5')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jladage/git/ladage.odoo/parts/odoo/odoo/addons/base/ir/ir_http.py", line 108, in _authenticate
    request.session.check_security()
  File "/Users/jladage/git/ladage.odoo/parts/odoo/odoo/http.py", line 1058, in check_security
    self.session_token = security.compute_session_token(self)
  File "/Users/jladage/git/ladage.odoo/parts/odoo/odoo/service/security.py", line 18, in compute_session_token
    return self._compute_session_token(session.sid)
  File "<decorator-gen-62>", line 2, in _compute_session_token
  File "/Users/jladage/git/ladage.odoo/parts/odoo/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/Users/jladage/git/ladage.odoo/parts/odoo/odoo/addons/base/res/res_users.py", line 528, in _compute_session_token
    WHERE id=%%s""" % (session_fields), (self.id,))
  File "/Users/jladage/git/ladage.odoo/parts/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/Users/jladage/git/ladage.odoo/parts/odoo/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column "value" does not exist
LINE 1: ...h_access_token, password, password_crypt, (SELECT value FROM...
```

**Comment by yelizariev** [comment]
We are aware of the problem. 
Workaround is done in https://github.com/it-projects-llc/misc-addons/pull/565, but for 10.0 only

Also, more proper solution is almost done in https://github.com/it-projects-llc/misc-addons/pull/568. I'm going to add migration scripts there for safe update from previous versions of the module. You are welcome to try the PR

I'll merge updates to 11.0 after #568

**Comment by jladage** [comment]
I tried to update to the latest version, but it crashed with a column 'value' already exists.
To make your code a bit more robust you can first verify if the column is there and return.
```
    # Create Column value if it doesn't exist yet. This is the case if you
    # installed a previous version started on 10.0
    cr.execute(
        'SELECT count(attname) FROM pg_attribute '
        'WHERE attrelid = '
        '( SELECT oid FROM pg_class WHERE relname = %s ) '
        'AND attname = %s',
        ('ir_config_parameter', 'value'))
    if cr.fetchone():
        return
    cr.execute("ALTER TABLE ir_config_parameter ADD COLUMN value VARCHAR")
```

Other than that your fixes are great!

**Comment by yelizariev** [comment]
It's fixed now and works stable. Let me know if it's not
