### ISSUE TITLE
ir_attachment_force_storage for odoo 10.0

### ISSUE THREAD

**Issue by cmutz** [itpp-labs/misc-addons#589]
Hello,

I installed the module **ir_attachment_force_storage** on my server odoo in version 10.0 up to date and
the module doesn't work.
When I move the filestores, my odoo doesn't work.

`IOError: [Errno 2] No such file or directory: u'/opt/odoo/.local/share/Odoo/filestore/PROD_2604201801/3c/3cb326e410685aee2c1309a0f02b6a237ca59b0b'
2018-05-02 10:27:43,156 9399 INFO PROD_2604201801 odoo.addons.base.ir.ir_attachment: _read_file reading /opt/odoo/.local/share/Odoo/filestore/PROD_2604201801/44/4452088b8bd8ed0fef0e76eab482785cd80ce534
`
Can you help me ?

Regards
Clement

**Comment by yelizariev** [comment]
Are you sure, that the module is really installed and you didn't change ``ir_attachment.location`` parameter?

**Comment by cmutz** [comment]
Hello and thank you for your answer.

How can be sure that module is installed ? 
I can see module installed
![capture1](https://user-images.githubusercontent.com/14125233/39565682-2e290e44-4eb9-11e8-801f-27be7287fe1f.PNG)
I changed parameter ir_attachment.location
![capture2](https://user-images.githubusercontent.com/14125233/39565780-9a9236f0-4eb9-11e8-90d6-9f3ed3bbe103.PNG)

Regards,

**Comment by cmutz** [comment]
Hello,

Have you an idea for problem ? 
How can you debuging the module ?
Regards,
Clement

**Comment by cmutz** [comment]
Hello,

I unistall the module and I install again the module.
I have this error : 

Traceback (most recent call last):
  File "/opt/odoo/server/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/server/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/server/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/server/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/server/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/server/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/server/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/server/addons/web/controllers/main.py", line 896, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/server/addons/web/controllers/main.py", line 884, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/server/odoo/addons/base/module/module.py", line 411, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/server/odoo/addons/base/module/module.py", line 485, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/extra-addons/odoo_addons/smile_upgrade/models/registry.py", line 44, in new
    return native_new(db_name, force_demo, update_module=update_module)
  File "/opt/odoo/server/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/server/odoo/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/server/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/server/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/server/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/server/odoo/tools/convert.py", line 843, in convert_file
    convert_yaml_import(cr, module, fp, kind, idref, mode, noupdate, report)
  File "/opt/odoo/server/odoo/tools/yaml_import.py", line 944, in yaml_import
    yaml_interpreter.process(yaml_string)
  File "/opt/odoo/server/odoo/tools/yaml_import.py", line 880, in process
    self._process_node(node)
  File "/opt/odoo/server/odoo/tools/yaml_import.py", line 893, in _process_node
    self.process_python(node)
  File "/opt/odoo/server/odoo/tools/yaml_import.py", line 608, in process_python
    unsafe_eval(code_obj, {'ref': self.get_id}, code_context)
  File "/opt/odoo/extra-addons/misc-addons/ir_attachment_force_storage/pre_install.yml", line 4, in <module>
    self.set_param("ir_attachment.location", "postgresql:lobject")
  File "/opt/odoo/server/odoo/addons/base/ir/ir_config_parameter.py", line 105, in set_param
    self.create(vals)
  File "/opt/odoo/extra-addons/misc-addons/ir_attachment_force_storage/models.py", line 22, in create
    self._attachment_force_storage(default_value)
  File "/opt/odoo/extra-addons/misc-addons/ir_attachment_force_storage/models.py", line 15, in _attachment_force_storage
    self.env['ir.attachment'].force_storage_previous(previous_value=previous_value)
  File "/opt/odoo/extra-addons/misc-addons/ir_attachment_force_storage/models.py", line 74, in force_storage_previous
    attach.write({'datas': attach.datas, 'url': attach.url})
  File "/opt/odoo/server/odoo/fields.py", line 915, in __get__
    self.determine_value(record)
  File "/opt/odoo/server/odoo/fields.py", line 1027, in determine_value
    self.compute_value(recs)
  File "/opt/odoo/server/odoo/fields.py", line 981, in compute_value
    self._compute_value(records)
  File "/opt/odoo/server/odoo/fields.py", line 972, in _compute_value
    getattr(records, self.compute)()
  File "/opt/odoo/extra-addons/misc-addons/ir_attachment_url/models/ir_attachment.py", line 16, in _compute_datas
    r = requests.get(attach.url)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 431, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 379, in prepare_url
    raise MissingSchema(error)
MissingSchema: Invalid URL '/website/static/src/img/library/bridge.jpg': No schema supplied. Perhaps you meant http:///website/static/src/img/library/bridge.jpg?


Any idea ?

Regards,
Clement

**Comment by trojikman** [comment]
Hello, I could not reproduce this error. Feel free to reopen it if you have additional information.
