### ISSUE TITLE
Error on inserting HTML Tags in the signature of res_users_signature 

### ISSUE THREAD

**Issue by anj4u** [itpp-labs/misc-addons#6]
When creating the signature, all is ok, but if I select at least 1 user, and push save or update signatures, i get this exception:

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 526, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 563, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 792, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 949, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 393, in old_api
    result = new_api(recs, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 397, in new_api
    result = [method(rec, _args, *_kwargs) for rec in self]
  File "/opt/odoo/odoo-server/addons/res_users_signature/res_users_signature_models.py", line 78, in write
    self.action_update_signature()
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 397, in new_api
    result = [method(rec, _args, *_kwargs) for rec in self]
  File "/opt/odoo/odoo-server/addons/res_users_signature/res_users_signature_models.py", line 83, in action_update_signature
    self.user_ids.render_signature_id()
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 397, in new_api
    result = [method(rec, _args, *_kwargs) for rec in self]
  File "/opt/odoo/odoo-server/addons/res_users_signature/res_users_signature_models.py", line 37, in render_signature_id
    mako = mako_template_env.from_string(tools.ustr(self.signature_id.template))
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 841, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 554, in compile
    self.handle_exception(exc_info, source_hint=source)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<unknown>", line 1, in template
TemplateSyntaxError: unexpected '<'

**Comment by anj4u** [comment]
Solved the problem, it was just about the syntax in variables, my export function destroyed it, sorry for the wrong issue.
