### ISSUE TITLE
mail_sent causes read access error on delete

### ISSUE THREAD

**Issue by JosDeGraeve** [itpp-labs/misc-addons#90]
Hi Ivan,

First thank you for publishing your modules, you really have some very nice stuff here.

There is an issue with your module mail_sent.

With that module installed, i get a **read access error** when as a non admin user,  trying to **unlink** a record from any object inheriting from mail_tread.  Uninstalling the module fixes the issue.

For some reason, odoo.addons.mail.mail_message.mail_message#check_access_rule is called multiple times, but the last call an "Access Denied" error is raised.

I havn't got around to figuring out why this is, we just have disabled the module for now.  I wanted to share my findings just in case you face a simular issue.

```
2015-11-24 18:12:13,968 3674 DEBUG vagrant openerp.addons.mail.mail_message: check_access_rule called with params:
2015-11-24 18:12:13,969 3674 DEBUG vagrant openerp.addons.mail.mail_message: uid: 24, ids: [2544237], operation: unlink
2015-11-24 18:12:13,980 3674 DEBUG vagrant openerp.addons.mail.mail_message: check_access_rule called with params:
2015-11-24 18:12:13,980 3674 DEBUG vagrant openerp.addons.mail.mail_message: uid: 24, ids: [2544237], operation: read
2015-11-24 18:12:14,014 3674 DEBUG vagrant openerp.addons.mail.mail_message: check_access_rule called with params:
2015-11-24 18:12:14,014 3674 DEBUG vagrant openerp.addons.mail.mail_message: uid: 24, ids: [2544237], operation: unlink
2015-11-24 18:12:14,213 3674 DEBUG vagrant openerp.addons.mail.mail_message: check_access_rule called with params:
2015-11-24 18:12:14,214 3674 DEBUG vagrant openerp.addons.mail.mail_message: uid: 24, ids: [2544237], operation: read
2015-11-24 18:12:14,220 3674 ERROR vagrant openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/8.0/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/8.0/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/8.0/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/8.0/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/8.0/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/8.0/odoo/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/8.0/odoo/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/8.0/odoo/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/8.0/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/8.0/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/8.0/odoo/addons/mail/mail_thread.py", line 453, in unlink
    msg_obj.unlink(cr, uid, msg_ids, context=context)
  File "/opt/odoo/8.0/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/8.0/odoo/addons/mail/mail_message.py", line 842, in unlink
    return super(mail_message, self).unlink(cr, uid, ids, context=context)
  File "/opt/odoo/8.0/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/8.0/odoo/openerp/models.py", line 3673, in unlink
    recs.recompute()
  File "/opt/odoo/8.0/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/8.0/odoo/openerp/models.py", line 5753, in recompute
    name: rec[name] for name in names
  File "/opt/odoo/8.0/odoo/openerp/models.py", line 5753, in <dictcomp>
    name: rec[name] for name in names
  File "/opt/odoo/8.0/odoo/openerp/models.py", line 5637, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/8.0/odoo/openerp/fields.py", line 819, in __get__
    self.determine_value(record)
  File "/opt/odoo/8.0/odoo/openerp/fields.py", line 897, in determine_value
    self.compute_value(recs)
  File "/opt/odoo/8.0/odoo/openerp/fields.py", line 877, in compute_value
    self._compute_value(records)
  File "/opt/odoo/8.0/odoo/openerp/fields.py", line 869, in _compute_value
    self.compute(records)
  File "/opt/odoo/8.0/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/8.0/odoo/openerp/api.py", line 416, in new_api
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo/8.0/addons-enabled/mail_sent/models.py", line 9, in _get_sent
    self.sent = len(self.notified_partner_ids) > 1 or len(self.notified_partner_ids)==1 and self.notified_partner_ids[0].id != self.author_id.id
  File "/opt/odoo/8.0/odoo/openerp/fields.py", line 819, in __get__
    self.determine_value(record)
  File "/opt/odoo/8.0/odoo/openerp/fields.py", line 912, in determine_value
    record._prefetch_field(self)
  File "/opt/odoo/8.0/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/8.0/odoo/openerp/models.py", line 3241, in _prefetch_field
    result = records.read(list(fnames), load='_classic_write')
  File "/opt/odoo/8.0/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/8.0/odoo/openerp/api.py", line 565, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/opt/odoo/8.0/odoo/addons/mail/mail_message.py", line 827, in read
    self.check_access_rule(cr, uid, ids, 'read', context=context)
  File "/opt/odoo/8.0/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/8.0/odoo/addons/website_mail/models/mail_message.py", line 89, in check_access_rule
    return super(MailMessage, self).check_access_rule(cr, uid, ids=ids, operation=operation, context=context)
  File "/opt/odoo/8.0/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/8.0/odoo/addons/portal/mail_message.py", line 63, in check_access_rule
    return super(mail_message, self).check_access_rule(cr, uid, ids=ids, operation=operation, context=context)
  File "/opt/odoo/8.0/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/8.0/odoo/addons/mail/mail_message.py", line 770, in check_access_rule
    (self._description, operation))
except_orm: (u'Toegang geweigerd', u'The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: Message, Operation: read)')
```

Kind Regards,
Jos

**Comment by yelizariev** [comment]
Hi,

Is it some custom model you trying to delete? Is it possible, that you lost access to that record right after you trying to delete it?

**Comment by JosDeGraeve** [comment]
Hi,

The model i tested with was "note.note".  The error occurred with these other models too:
- crm.lead
- sale.order
- account.invoice

Regards,

**Comment by yelizariev** [comment]
Fixed

**Comment by yelizariev** [comment]
Thanks for report
